language: java
jdk:
  - oraclejdk8
after_success:
  - echo "<settings><servers><server><id>arpinum</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASSWORD}</password></server></servers></settings>" > ~/settings.xml
  - mvn deploy --settings ~/settings.xml
